service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-south-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: twitterbotLikes
    handler: lambda_function.lambda_handler
    description: Periodically check the twitter bot's timeline and like any tweet that @mentions it.
    timeout: 30 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"